### ISSUE TITLE
Log cleanup doesn't work

### ISSUE THREAD

**Issue by jochenwezel** [CompuMasterGmbH/cammIntegrationPortal#57] opened 2018-02-19 13:29 UTC
The options are defined as following:
![image](https://user-images.githubusercontent.com/3033827/36379911-ab7fd71e-1580-11e8-9254-f371c96b6647.png)

Following first entry in table LOG is not getting dropped:
![image](https://user-images.githubusercontent.com/3033827/36379956-d8e455ae-1580-11e8-941a-024720745a55.png)

It should be dropped for 3 reasons:
1. RuntimeInformation retention days are 30 days - and already over
2. General retention days are 90 days - and already over, too
3. General max. log items count is 300,000, but there is already > 1,000,000

**Comment by jochenwezel** [comment] 2018-02-19 13:31
FYI: WebCron works
![image](https://user-images.githubusercontent.com/3033827/36380137-7d2932e2-1581-11e8-8508-c2072e063594.png)

**Comment by cmalbertschw** [comment] 2018-03-08 16:36
>RuntimeInformation retention days are 30 days - and already over

These weren't properly matched. This was an error in the UI, fixed in ee57164af385e28453295d2926007b3bfd5bfcc7 

>General retention days are 90 days - and already over, too

Specific settings win over the general ones, therefore the fact this setting did not remove the log entries in question is by design.

>General max. log items count is 300,000, but there is already > 1,000,000

Fixed by 0ea0b41850b9514556ebae5d37b4017ffec4edde

**Closed as completed by cmalbertschw** 2018-03-08 16:36 UTC
Labels: bug, core, priority
